### ISSUE TITLE
bzip2ed logs causes check for Nightly Maintenance to fail

### ISSUE THREAD

**Issue by ChaosAdventurer** [snielson/dsapp_python#12]
dsapp 232 on SLES 11.3
datasync-*-2.1.0.5733-1.1
connects to a pair of GroupWise 2012 SP4 POAs
logrotate.d has all the datasync logs compressed with bkip2 and I've not touched that line in them, and nobody else has been on this system at this level.  Other clients are all gzip,  

Checking Nightly Maintenance..    Traceback (most recent call last):
  File "/opt/novell/datasync/tools/dsapp/dsapp.py", line 610, in <module>
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_menus.py", line 138, in main_menu
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_menus.py", line 485, in checksQueries_menu
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_ghc.py", line 223, in generalHealthCheck
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_ghc.py", line 816, in ghc_verifyNightlyMaintenance
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_Definitions.py", line 2046, in checkNightlyMaintenance
  File "/usr/lib64/python2.6/gzip.py", line 438, in next
    line = self.readline()
  File "/usr/lib64/python2.6/gzip.py", line 393, in readline
    c = self.read(readsize)
  File "/usr/lib64/python2.6/gzip.py", line 219, in read
    self._read(readsize)
  File "/usr/lib64/python2.6/gzip.py", line 255, in _read
    self._read_gzip_header()
  File "/usr/lib64/python2.6/gzip.py", line 156, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

/opt/novell/datasync/tools/dsapp/logs/dsapp.log ends in 
[2016-03-24 16:08:44 EDT][INFO][checkNightlyMaintenance] Scannning logs for maintenance..
[2016-03-24 16:08:47 EDT][INFO] ------------- Successfully shutdown dsapp -------------

So if not ASCII or gzipped, either state unsupported format or actually test for and use bzip2.

**Comment by ChaosAdventurer** [comment]
and I have run dsapp Health Checks on this site many times before, last on version 277

**Comment by snielson** [comment]
That's odd.. I was under the assumption that all log compress commands used 'compresscmd /usr/bin/gzip' in the logrotate files.

I'll do some playing around with the standard bz2 library, and write up a method to detect, and use the correct decompression

**Comment by ChaosAdventurer** [comment]
Perhaps in the past, as the one remaining SLES9/OES1 box I have access to does gzip, where as all the SLES10+ boxes I've looked at default to bzip when no compresscmd was specified in the logrotate.d files.  A good point to ask at my local SUSE days next week.

**Comment by snielson** [comment]
Wouldn't the datasync-* logrotate files come from the datasync / GMS install, and not so much the OS? All my test servers are SLES 11+, and are set up to use gzip.

Perhaps the version of mobility that was installed?
Either way I'll lets make this work for either gzip or bzip2

**Comment by snielson** [comment]
Put fix into v233 to check file extension, and use either gzip or bzip2

**Comment by ChaosAdventurer** [comment]
yes, the datasync-* logrotate files came from the GMS install,  I think that box was 2.0 and updated to 2.1.  interestingly this particular system's logrotates have a timestamp when I was around, but didn't do any work on that set of systems, hmmm    I was more noting the general change in SLES logrotate compress.  so how long for the update to be live for dsapp to see it?

**Comment by snielson** [comment]
Just pushed v233
https://github.com/snielson/dsapp_python/releases/tag/2.00-233

Let me know how it works out. If things go well I can update the build and version for the auto-update.

**Comment by ChaosAdventurer** [comment]
It still shows as v232 when running the health check, as well as for 2, 4, & 5 of the "Checks & Queries" even though most spots show v233 as expected.
I see that it reads the memory properly now on this system, it was having issues after we increased it to 6GB.
hmm, user (null) has 10 Events. something for me to look up tomorrow.
Otherwise looks good, but then I don't have anything to really push it tonight. Have a Happy Easter.

**Comment by snielson** [comment]
I can't seem to duplicate the wrong version showing up in those menus. However some of the imported py files read from the dsapp settings.cfg file.

Maybe it wasn't updated correctly? /opt/novell/datasync/tools/dsapp/conf/setting.cfg
A quick reinstall of dsapp may clear this up.

Remove the rpm `rpm -e dsapp`, and install the new v233 `rpm -ivh dsapp-2.00-233.noarch.rpm`

Thanks again.. Happy Easter!

**Comment by ChaosAdventurer** [comment]
that cleared it up.  thank you.
