### ISSUE TITLE
dsapp -v -i doesn't start mobility services from GMS

### ISSUE THREAD

**Issue by korth1** [snielson/dsapp_python#16]
We run dsapp.sh version 234, 3 times a week with dsapp.sh -v -i to index and vacuum the postgresql database. This first stops GMS services, do his job, and then starts GMS services again. But at the end of this action it comes with an error : 
NOTICE:  table "attachments" was reindexed
REINDEX
Starting Mobility.. [/]..failed   
GMS services looks to run, but when we goto to the GUI from GMS, both agents are still on 'STOPPED'.
We run GMS2014R2. So how can this happen? or Solved? kind regards, Henk Korterink

**Comment by snielson** [comment]
are you able to manually start it with `rcgms start` ?

**Comment by korth1** [comment]
Yes, when i do a rcgms restart, then it stops/start the GMS services, and then not only on cli the services are running, but also on the GUI the agents are running. In the past we did not have this problem. Maybe a combination of gw2014R2 with dsapp.sh 234 (232 did also have the same problem).

**Comment by snielson** [comment]
Any chance you can apply this v235 dsapp, and set the logs to debug.
After you run the vacuum and index, please attach the dsapp.log

Remove old dsapp
`rpm -e dsapp`
Install new FTF dsapp v235
`rpm -ivh dsapp-2.00-235.noarch.rpm`
Set logging to debug
`dsapp --setlog debug`
Run vacuum and index
`dsapp -v -i`

The logs are at /opt/novell/datasync/tools/dsapp/logs/dsapp.log
ftp://ftp.novell.com/outgoing/dsapp-235-FTF.zip

**Comment by korth1** [comment]
Thank you snielson for this very quick reply. Very Great!!
[Dsapp failed.docx](https://github.com/snielson/dsapp_python/files/196428/Dsapp.failed.docx)
 We did run the v235FTF dsapp.sh but this still have the same behaviour. The dsapp.log doesn't mentioned something is wrong. But the Log file wich is made by the script where dsapp.sh is started in, does. Looks like the starting off the different services from datasync-xxx has another impact, than starting the GMS services with rcgms restart. But i don't know the difference between this too. I attachted also a word document with printscreens.

**Comment by snielson** [comment]
that v235 just had some increased logging.
dsapp.sh was actually able to use rcgms [start,stop,restart]

However the rcgms script looks for any python pid in /opt/novell/datasync to report any problem shutting down GMS. Unfortunately dsapp also runs under this path, so I had to get creative on how to stop or start processes

Could you upload the logs from dsapp (options 1,1) If you have FTP access, please upload. When prompted for a SR number, put in "dsapp_python_16"

**Comment by snielson** [comment]
Actually I may have found the issue.. working a fix now..

**Comment by snielson** [comment]
Ok I uploaded what I believe will fix it
ftp://ftp.novell.com/outgoing/dsapp-235-FTF.zip

Just remove the old rpm `rpm -e dsapp`
and install this new one `rpm -ivh dsapp-2.00-235.noarch.rpm`

You were right about the order the agents started. Somehow during the script lookup, it placed the syncengine to start before the configengine, which caused this problem. I've now hard coded the order.

**Comment by korth1** [comment]
Hello snielson, this works !! This is the last rule in the log from my script: 
NOTICE:  table "attachments" was reindexed
REINDEX
Starting Mobility.. [/]
So no error anymore. in CLI the services are running, AND also in the GUI the agents are running.!
So your change was good.!! Thank you for your quick support. Very good. Kind regards, Henk Korterink.

**Comment by korth1** [comment]
Hallo snielson, when we start dsapp.sh is still said version v234. So something to think about.

**Comment by snielson** [comment]
Correct, this v235 was a test build for you to validate a working fix. Since the autoupdate checks the version, I'd hate for you to miss any autoupdate for a one off v235 fix.

Once the 'official' v235 is live, the version will also reflect that.

Glad to hear that fix worked.
