### ISSUE TITLE
Self signed certificates are created with SHA1 hash algorithm 

### ISSUE THREAD

**Issue by dkrotil** [snielson/dsapp_python#17]
Hi,
I just created self signed certificates with help of dsapp and they are with SHA1 hash algorithm, is there a way to change dsapp to create certificates with SHA256 ?

Thanks

David

**Comment by snielson** [comment]
Added sha256 for self signed certs. Let me know if this build of v234 works for you.
ftp://ftp.novell.com/outgoing/dsapp-234-FTF.zip

**Comment by dkrotil** [comment]
It´s working, thanks a lot.
