### ISSUE TITLE
General Health check hangs after "Checking Reference Count.. Passed"

### ISSUE THREAD

**Issue by jvz1984** [snielson/dsapp_python#19]
Hi Shane,

I just updated our dsapp on GMS2014R2 server to 235, and running the GHC stops working where it would finish fast before. I'm not sure whether this is related to our situation but i'd like to rule that out.

I start the tool via de dsapp.sh file.
I hope you can do something with the break output as attached.
[dsapp-break.txt](https://github.com/snielson/dsapp_python/files/224111/dsapp-break.txt)

information which might be of use:
I use a .pgpass file for another script i use. But i've also tested this after renaming that file.
When using v227 just half hour before, it would start asking the database user password around that point (not sure if exact that point, and not sure why). This question would repeat itself for all remaining ghc steps. I don't see this output now. It used to continue to work when i typed the database user's password there.
With a bit of work i can get that version back up if you like.
Upgraded using rpm -U
Setup: 1xGMS and 1xGW 2014R2

Would love to hear from you.

**Comment by snielson** [comment]
I'm sorry to hear dsapp v235 isn't working for you, however thanks for taking time to open a new issue!

The old dsapp v227 is still available with the new python build. That can be found at /opt/novell/datasync/tools/dsapp/dsapp.org.sh 

Since I've rewritten dsapp in python, I've moved away from using the .pgpass file, where 227 would need it, and attempt to create one if not found.

Would you mind setting the logs to debug for dsapp, and sending me both the dsapp.log and exception.log?
`dsapp --setlog debug`

The logs can be found in /opt/novell/datasync/tools/dsapp/logs/
Either upload them to the issue or email them directly to me at snielson@projectuminfinitas.com

**Comment by jvz1984** [comment]
Here you go.
[logs.zip](https://github.com/snielson/dsapp_python/files/225728/logs.zip)
Let me know if i can be of any further assistance.

**Comment by snielson** [comment]
So of course the logging I put into that section was slacking.. 
I did find at least which line it was hanging, and put a lot more logging around it.

Would you mind installing this newer version of 235, and repeat the steps for better logging?
https://filr.attachmategroup.com/ssf/s/readFile/share/69136/-6972677436083209447/publicLink/dsapp-235-FTF.zip

We'll need to remove the old rpm first, and put the new one down. Which means we'll need to increase the logging to debug one more time.

Remove dsapp
`rpm -e dsapp`

Install dsapp 235
`unzip dsapp-235-FTF.zip`
`rpm -ivh dsapp-2.00-235.noarch.rpm`

Set logging to debug
`dsapp --setlog debug`

This will have all these changes if you're curious
* Added debug logging for every settings.cfg write
* Added extra debug logging to show_GW_syncEvents()
* Added deviceid to whereDidIComeFromAndWhereAmIGoingOrWhatHappenedToMe() output
* Added debug logging to ghc_checkUserFDN()
* Removed eContinue() from --bug switch
* Removed extra psql search in dCleanup()
* Added verifyUser() to accept multiple IDs. Separated by a comma ','
* Changed monitorUser() to accept multiple IDs
* Changed setUserState() to accept multiple IDs
* Changed remove_user() (force) to accept multiple IDs

**Comment by jvz1984** [comment]
Somehow it does finish now. Though it does take a long time. Especially on this line, which also has a typo :) but i guess that's because we block outgoing connections and it gets a timeout on external NTP server.
Checking Sever Date..             Failed
Exceptions log hasn't changed this time. I'm assuming because there was no exception code this time.
[dsapp.zip](https://github.com/snielson/dsapp_python/files/227388/dsapp.zip)

**Comment by snielson** [comment]
Lol thanks for pointing out that typo.

I wonder if the slight change in the ldap search to only request the cn per user helped that section finish.

Seems the one time killer is the ghc_verifyServerDate. I'll need to add a timeout, because any single check over a minute IMO is WAY to long.

**Comment by jvz1984** [comment]
I agree yes, 30 seconds should already be more than enough for a time-out detection. It rarely goes over 10 seconds when checking ntp i think. And perhaps add a small note about the timeout on the visible line so people know they have to wait at least that amount of seconds.

I was also wondering if the NTP address is read from the system settings or if it's an address you added yourself? If it's read from the system it seems i forgot to add ntp settings to this server :)

**Comment by snielson** [comment]
The timeout is actually set to 2 seconds for everything now.

As for the NTP address - time.nist.gov is one I added (can be changed in the /opt/novell/datasync/tools/dsapp/conf/setting.cfg). However it should also check all NTP addresses configured on the server.

Try this new 235 build (no need to mess with logged or upload them, unless it still has problems)
https://filr.attachmategroup.com/ssf/s/readFile/share/69196/-6297931950307713010/publicLink/dsapp-235-FTF-2.zip

**Comment by snielson** [comment]
Also.. the FTF-2 doesn't have the typo fix... but it is fixed now.

**Comment by jvz1984** [comment]
Alright it's starting to look good. NTP was indeed not configured, so I've also fixed that now and it passed afterwards. The ghc runs through all the steps at a reasonable speed now.

Just the warning for Proxy configuration I'm wondering what's wrong there. But i'll look through the recommended TID's first.

Thanks so far Shane!

**Comment by snielson** [comment]
Glad to hear it is finishing at a reasonable speed now.

Fix in v236

**Comment by jvz1984** [comment]
Thanks!
