### ISSUE TITLE
"Show GW events by User (consumerevents)" shows only a blank user in user column

### ISSUE THREAD

**Issue by tdharris** [snielson/dsapp_python#20]
"Show GW events by User (consumerevents)" option in dsapp shows only a blank user in user column. It doesn't find any users in the `consumerevents` table where `edata` contains `sourceName`, but will work if `sourceDN` is used.

Here is the line in a `dsapp.sh` where it dumps the consumerevents table, counts events, sorts, groups:
```pg_dump -U datasync_user -t consumerevents datasync | awk '!/<.*>/' RS="<"sourceName">|</"sourceName">" | sort | uniq -c | sort -nr```

If `sourceName` is replaced with `sourceDN`, it seems to resolve the issue; however, it should be verified if both can be valid, which case an or condition can be used here in the awk. 

We ran this command manually, which gave us the results we were looking for:
```pg_dump -U datasync_user -t consumerevents datasync | awk '!/<.*>/' RS="<"sourceDN">|</"sourceDN">" | sort | uniq -c | sort -nr```

**Comment by snielson** [comment]
Changed if statement from
`if '<sourceName>' in row['edata']:`
to
`if '<sourceName>' in row['edata'] or '<sourceDN>' in row['edata']:`

Should now catch both for backwards compatibility.

**Comment by snielson** [comment]
Fixed in v236
