### ISSUE TITLE
(Enh) Monitor incoming device requests and their impact on the mobility server

### ISSUE THREAD

**Issue by tdharris** [snielson/dsapp_python#21]
Had a scenario where all device threads were always in use on a mobility server and these were helpful in identifying which devices were problems so they could be blocked and their users migrated to another server for testing. Also would be helpful in identifying repeated/duplicated requests from a device slowing down the mobility server.

The following were recently helpful and could be incorporated into dsapp:

- Go through log and determine which devices (deviceId) have the most incoming requests:
```grep -Po "(?<=DeviceId=)[^<]*(?=&)" mobility-agent.log | sort | uniq -c```
<p><i>Note: This can be changed to include more or less of the query string to show what type of requests and on behalf of what user in addition to the deviceId.</i></p>

- Live log capture of incoming device requests (should show query string that includes device,user,ip,etc):
```tailf mobility-agent.log | grep -Po "(?<='QUERY_STRING':)[^<]*(?=', 'CONTENT)" | sed "s/^/$(date)/"```

**Comment by snielson** [comment]
Closing - See [issue](issue/22)
