### ISSUE TITLE
dsapp fails after update to dsapp-2.00-237

### ISSUE THREAD

**Issue by vruzicka** [snielson/dsapp_python#25]
Hi 
please help with this issue.

last version that did run ok:
 dsapp-1.00-227.noarch.rpm

xxxx:/home/install # rpm -Uvh dsapp-2.00-237.noarch.rpm
 Preparing... ########################################### [100%]
 1:dsapp ########################################### [100%]

dss-vmw-01:/home/install # dsapp
 Traceback (most recent call last):
 File "/opt/novell/datasync/tools/dsapp/dsapp.py", line 145, in 
File "/opt/novell/datasync/tools/dsapp/lib/dsapp_Definitions.py", line 11, in 
ImportError: No module named rpm

--------------------------------------------------------------------------------

:/home/install # ls -alth /opt/novell/datasync/tools/dsapp/lib/
 total 560K
 drwxr-xr-x 6 root root 4.0K Jun 24 13:30 .
 drwxr-xr-x 3 root root 4.0K Jun 24 13:30 lxml
 drwxr-xr-x 2 root root 4.0K Jun 24 13:30 psycopg2
 drwxr-xr-x 8 root root 4.0K Jun 24 13:30 suds
 drwxr-xr-x 5 root root 4.0K Jun 24 13:30 wsdl
 drwxr-xr-x 9 root root 4.0K Jun 24 13:30 ..
 -rw-r--r-- 1 root root 66K Jun 1 21:40 argparse.pyc
 -rw-r--r-- 1 root root 108K Jun 1 21:40 dsappDefinitions.pyc
 -rw-r--r-- 1 root root 8.2K Jun 1 21:40 dsappSoap.pyc
 -rwxr--r-- 1 root root 139K Jun 1 21:40 dsapp_Definitions.pyc
 -rwxr--r-- 1 root root 12K Jun 1 21:40 dsapp_Soap.pyc
 -rwxr--r-- 1 root root 49K Jun 1 21:40 dsapp_ghc.pyc
 -rwxr--r-- 1 root root 20K Jun 1 21:40 dsapp_menus.pyc
 -rwxr--r-- 1 root root 8.3K Jun 1 21:40 dsapp_performance.pyc
 -rwxr--r-- 1 root root 14K Jun 1 21:40 dsapp_re.pyc
 -rw-r--r-- 1 root root 946 Jun 1 21:40 filestoreIdToPath.pyc
 -rw-r--r-- 1 root root 1.6K Jun 1 21:40 getch.pyc
 -rw-r--r-- 1 root root 15K Jun 1 21:40 menus.pyc
 -rwxr--r-- 1 root root 14K Jun 1 21:40 ntplib.pyc
 -rw-r--r-- 1 root root 1.5K Jun 1 21:40 spin.pyc
 -rw-r--r-- 1 root root 33K Jun 1 21:40 tabulate.pyc

--------------------------------------------------------------------------------

xxxx:/home/install # uname -a
 Linux xxxx 3.0.101-71-default #1 SMP Thu Mar 3 12:56:15 UTC 2016 (7bdad2e) x86_64 x86_64 x86_64 GNU/Linux
 xxx:/home/install # cat /etc/SuSE-release
 SUSE Linux Enterprise Server 11 (x86_64)
 VERSION = 11
 PATCHLEVEL = 4

Many thanks 
Volkmar

**Comment by snielson** [comment]
I have test build of dsapp-237.rpm I can send you. I've included the rpm module. However these modules should be included into the /usr/lib64/python2.6/site-packages/ directory.

Please email me at snielson@projectuminfinitas.com to receive this test build

I'd be curious if other modules are missing from this path

**Comment by snielson** [comment]
included rpm module with dsapp
Fix in v238
