### ISSUE TITLE
Error in upgrade from v236 to v237

### ISSUE THREAD

**Issue by tdharris** [snielson/dsapp_python#26]
The following issue is from:
https://www.novell.com/communities/coolsolutions/cool_tools/dsapp/#comment-520597

"After update to latest version I get errors:
v236 (v237 available)
Updating dsapp to v237
Downloading https://github.com/snielson/dsapp_python/releases/download/latest/dsapp.zip [-]

This will update to:
dsapp-2.00-237

Updating.. [|]
Update complete

Exiting dsapp..
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/opt/novell/datasync/tools/dsapp/lib/spin.py", line 20, in run
: 'NoneType' object has no attribute 'stdout'

Program seems to run fine however on one exception:
4. Certificates
1. Generate self-signed certificate
It will ask for directory to store certificates instead of where the CSR and Private key are located. Options 1 and 2 (Create CSR &amp; Private key) seem to be the same."

**Comment by snielson** [comment]
NoneType' object has no attribute 'stdout' has been resolved with the next release v238

Variable was not assigned when the spinner was forced to stop, and stdout could not write NoneType

**Comment by snielson** [comment]
> 4. Certificates
> 1. Generate self-signed certificate
> It will ask for directory to store certificates instead of where the CSR and Private key are located. Options 1 and 2 (Create CSR & Private key) seem to be the same."

This was a design choice, and can be changed to fit expected behavior.

**Comment by snielson** [comment]
Confirmed resolved from original reporter.
Also rewrote certificate menu / options to be more clear
Fix in v238
