### ISSUE TITLE
Folder structure problem with calendar: <Proxy Calendar Name>

### ISSUE THREAD

**Issue by mfaust78** [snielson/dsapp_python#29]
5 -> 2 -> "2. Check GroupWise folder structure" reports "Folder structure problem with calendar: <Proxy Calendar Name>" for all Proxy calendars in user mailboxes.
These folders (as proxy calendars) should (and are) not synchronized to the mobile, so why does it report a structure problem. gwchecks on the user look ok.

**Comment by snielson** [comment]
I can only duplicate this if I move the proxy calendar out from under the main calendar. Is that the case with your setup?

I know proxy calendar shouldn't even be looked at, and will work on fixing this. Just want to make sure I understand why it's reporting a error first.

**Comment by snielson** [comment]
check_subCalendars ignores the folder if folderType == 'Proxy'
Proxy calendars should no longer show up, regardless of structure.

Fix in v240

**Comment by mfaust78** [comment]
The proxy calendars are all below calendar folders (not directly in the main calendar) e.g.
Calendar
- Team 1 (Calendar Folder)
-- User A Proxy Calendar
-- User B Proxy Calendar
- Team 2 (Calendar Folder)
-- User C Proxy Calendar
-- User D Proxy Calendar
We advised all users to do so to group the proxies and simpler selection/deselection.

Fix sounds great. Thanks.
