### ISSUE TITLE
Enh: Add "List folders in User mailbox"

### ISSUE THREAD

**Issue by mfaust78** [snielson/dsapp_python#30]
Under "6. User Info" add a point which lists all folders in the mailbox (Name, Folder ID, Type, shared to/from).
Would be great for troubleshooting - mainly because the debug log only shows the Folder IDs and reverse lookup is not something handy. Further the 'shared' part would be great for the new shared folders feature.

**Comment by snielson** [comment]
Not sure if this is what you're looking for, however all this is easy to read from the --debugMenu option 1
`dsapp --debugMenu`

This is a hidden switch (Not listed in the dsapp (-h, --help), as it also contains a option to show all variables (contains passwords)

**Comment by mfaust78** [comment]
Thank. That is perfectly fine. Event get more information than I was looking for.
As the switch is hidden, I didn't know about it...
