### ISSUE TITLE
End: Add "Count shared folders/calendars/books"

### ISSUE THREAD

**Issue by mfaust78** [snielson/dsapp_python#31]
With the new (GMS 14.2.1) feature shared folders/calendars/books will be available which will pose additional load to the server. It would be great if dsapp would have a point to count the shared folders. For example for a single user the folders shared to others and folders shared from. Other possibility generate a list of all users and show the number of shared folders from (sharedToMe) and to (sharedTo).
This could be ran before activating the "shares" folders to estimate the additional load.

**Comment by snielson** [comment]
Counting every user could take a very long time if there are a lot of users. That would require a SOAP loginRequest and getFolderList for every user.

I'll include single and every user, and build a preview build of v240 for testing if you don't mind testing this?

**Comment by mfaust78** [comment]
I guess it will take a while for all users, but as I mostly see the 'all users' as pre-upgrade-task I guess it is ok.
Feel free to send me the preview build or link - I'll test it on my systems (5 User, 80 User, 250 User).

**Comment by snielson** [comment]
[dsapp-239v2.zip](https://github.com/snielson/dsapp_python/files/416462/dsapp-239v2.zip)
Let me know what you think (or if it even works..)

**Comment by mfaust78** [comment]
tested it and works.
You asked what I think and here it is:
- for the single user check, any chance you could print out the folders (name + ID) in addition to the total?
- as the run time for the all users is (as you predicted) long, could you output a status like "10 of 83 users done", "20 of 83 users done"... so one has a rough clue where the process stands
- Load on the GMS server is quite high for the all user. roughly 1/2 of the time one CPU is busy with the check.

**Comment by snielson** [comment]
- [ ] Print out the list of folder names + ID for a single user
- [ ] Output user count for all users
- [x] Add \n to end of file

For the load on GMS - I'll have to investigate why this uses up so much CPU
In the dsapp.log, do you have debug logging enabled? It should show a redirect if any are required.

**Comment by snielson** [comment]
[dsapp-239v3.zip](https://github.com/snielson/dsapp_python/files/416896/dsapp-239v3.zip)

Suggested changes added + a warning about the CPU for now.

**Comment by mfaust78** [comment]
Sorry for not being precise. Not the GMS service has high load, but the python process of dsapp. Will test again.

**Comment by mfaust78** [comment]
Is it intended that if a user is deactivated, dsapp can't list the folders?
Tried and got the following error:

> Problem with '<userCN>'
> User Database is temporarily disabled
> Traceback (most recent call last):
>   File "/opt/novell/datasync/tools/dsapp/dsapp.py", line 655, in <module>
>     menus.main_menu()
>   File "/opt/novell/datasync/tools/dsapp/lib/dsapp_menus.py", line 165, in main_menu
>     sub_menus[choice]()
>   File "/opt/novell/datasync/tools/dsapp/lib/dsapp_menus.py", line 389, in userIssue_menu
>     groupwiseChecks_menu()
>   File "/opt/novell/datasync/tools/dsapp/lib/dsapp_menus.py", line 450, in groupwiseChecks_menu
>     pydoc.pager(shared_list)
>   File "/usr/lib64/python2.6/pydoc.py", line 1315, in pager
>     pager(text)
>   File "/usr/lib64/python2.6/pydoc.py", line 1329, in <lambda>
>     return lambda text: pipepager(text, os.environ['PAGER'])
>   File "/usr/lib64/python2.6/pydoc.py", line 1356, in pipepager
>     pipe.write(text)
> TypeError: argument 1 must be string or read-only character buffer, not None

**Comment by snielson** [comment]
Yes that is normal for the loginRequest. If you actually run 5,2,1 (soap user check). It should show that description. This is simply the SOAP reply for that loginRequest.

I'll add in some error handling for any loginRequest which doesn't give back a good result.

**Comment by snielson** [comment]
[dsapp-239v4.zip](https://github.com/snielson/dsapp_python/files/419798/dsapp-239v4.zip)
Fixed the error traceback for any kind of failed soap loginRequest for shared single and all users.

**Comment by mfaust78** [comment]
Thank you for the explanation - makes sense now.
Change with regards traceback / error handling works. Thanks!

**Comment by mfaust78** [comment]
Questions regarding ContactsFolders / address books:
I did some more testing and saw that I can't get any information regarding shared address books. For example, if only an address book is shared (no other sharesTo/By), then dsapp (5,2,3) will show 0 shares, although there is a shared address book.
tried dsapp --debugMenu to get a full list. The list does not indicate any share on the address book / contact folder. For example the address book "M20" is shared but I only see:
`            (UserContactFolder){
               id = "57B32B41.do-city.po-city.100.1323472.1.41FB2.1@32"
               sid = 270258
               name = "M20"
               modified = 2016-08-16 14:03:29
               parent = "1B.do-city.po-city.100.0.1.0.1@32"
               sequence = 0
               folderType = "UserContacts"
               addressBook = "57B32B41.do-city.po-city.104.1323472.1.A8F.1@53"
            },`

**Comment by snielson** [comment]
Is the "ä" in a username or folder name?

I'm going to check with one of our GMS developers on the main contacts being shared. Just out of curiosity... does GMS handle that share fine?

**Comment by mfaust78** [comment]
The ä (or other umlaut for that matter) is in the folder name.

It's not the main contacts - its any contacts folder shared (the contacts folder in the example is called "M20"). GMS handles the shared contacts fine.
My user for example receives one shared contacts folder - which I have synced though GMS on my mobile - but it does not show up in the "Folders shared to mfa" list and using dsapp --debugMenu I see it as follows:
`            (UserContactFolder){
               id = "56F31E93.do-city.po-city.100.1323472.1.3CD42.1@32"
               sid = 249154
               name = "IT Shared (edv hotline)"
               modified = 2016-08-16 14:03:29
               parent = "1B.do-city.po-city.100.0.1.0.1@32"
               description = "Ihnen wurde der Zugriff auf mein Adressbuch mit dem Namen 'IT Shared' freigegeben."
               sequence = 1
               folderType = "UserContacts"
               addressBook = "56F31E93.do-city.po-city.104.1323472.1.A57.1@53"
            },
`

**Comment by snielson** [comment]
Trying a new soap method to get the shared address books.  Currently this shows the shared information the normal folderList does not.

Will work this into the shared check,

**Comment by snielson** [comment]
[dsapp-239v5.zip](https://github.com/snielson/dsapp_python/files/421076/dsapp-239v5.zip)
Updated to now check all shared address books as well.
pydoc.py was updated to handle unicode properly (Some characters may look different), but no longer crashes

**Comment by snielson** [comment]
I should add... the soap method to get the address books almost doubles the time it takes to total shares.

The runtimes from above:
> Runtime:
> about 8 Minutes for 83 Users / Total folders shared by: 87 / Total folders shared to: 1618
> about 32 Minutes for 317 Users / Total folders share by: 344 / Total folders shared to: 4422

 will probably take a little longer... if not doubled.

**Comment by mfaust78** [comment]
Thanks for the update. Did some testing and here my results:
- Now shows the shared address books. Thanks.
- If a account is disabled, that is shown twice - guess once for each test.
- it is slower. Runtime now: about 13 Minutes for 83 Users (+2/3)
- Install on SLES 12 server works, but can't start it:
```
Traceback (most recent call last):
  File "/opt/novell/datasync/tools/dsapp/dsapp.py", line 170, in <module>
    import dsapp_Definitions as ds
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_Definitions.py", line 11, in <module>
    import subprocess,socket,re,rpm,contextlib
  File "/opt/novell/datasync/tools/dsapp/lib/rpm/__init__.py", line 7, in <module>
    from _rpm import *
ImportError: librpmbuild-4.4.so: cannot open shared object file: No such file or directory```
But "/opt/novell/datasync/tools/dsapp/lib/librpmbuild-4.4.so" is there, but on the SLES 12 SP1 there are "/usr/lib64/librpmbuild.so.3.2.1" and "/usr/lib/librpmbuild.so.3.2.1" in the system lib path.

Any chance you could add the "originating" user in the "Folders shared to <userID>" section?
From Name and ID (example below) I could go and search in the mailbox, but if you would add "Shared By", it would be pretty straight forward to see where the origin of the data is.

**Comment by snielson** [comment]
- [ ] Perform SOAP loginRequest once for shared check
- [ ] Fix regression on SLES 12 install
- [ ] Add originating user to Shared By

I'll work on the above. Perhaps the single SOAP loginRequest will help with the check time, but doubt by much.

**Comment by snielson** [comment]
[dsapp-239v6.zip](https://github.com/snielson/dsapp_python/files/421446/dsapp-239v6.zip)
Hopefully this fixes those above issues for you. Cheers!

**Comment by mfaust78** [comment]
Thanks a lot!
Tested the issues and works fine on SLES 12 SP1, originating user is shown and performance looks good: Runtime about 10 Minutes for the 83 Users.
Only very minor thing I saw is that the email address for 'Shared By' is in the <CN>.<PO>.<DO>@<domain> notation, but I don't mind that...

**Comment by snielson** [comment]
Yeah.... unfortunately the folderListRequest gives the email back in that format. However, I believe I can store their actual email without  to much work.

Thanks for all your help testing, and feedback!

**Comment by mfaust78** [comment]
I agree that it is not worth the extra load / time.
Thank you for implementing everything! Was a pleasure to test and give feedback.
