### ISSUE TITLE
"SOAP - View user folder list" does not return result

### ISSUE THREAD

**Issue by mfaust78** [snielson/dsapp_python#32]
dsapp239v6 --debugMenu --> "1. SOAP - View user folder list" does not return any results anymore... does work on older version (like shipping v239).

**Comment by snielson** [comment]
Yeah.. that was my bad. I was doing some testing with folder lists, and forgot to change it back before making the 239 post build.

Already fixed it for v240

**Comment by mfaust78** [comment]
No problem. Glad it is fixed already. Looking forward to v240 then.
