### ISSUE TITLE
dsapp update with local ISO fails 

### ISSUE THREAD

**Issue by vruzicka** [snielson/dsapp_python#33]
Hi,
I have tried to update via dsapp and the following menus:
Select Register & Update | Update Mobility | Update with Local ISO
Enter y to give permission to restart GMS during the update procedure.
Provide the full path to the directory of the ISO file. 
novell-groupwise-mobility-service-14.2.0-x86_64-292-SLES11.iso

--> error message is: 
Unable to find content in ISO (novell- group....)
(this ISO file worked on another linux server OK - to let you know)

Please help me. Which logs or debug info do you need ?
(the server is not a full blown SLES11 SP4 installation it's a "reduced" version without GUI)
What package could me missing on this machine ? 
I can mount the ISO file OK with mount -o loop 

Thanks
Volkmar

**Comment by vruzicka** [comment]
we use dsapp version 2.00.239

**Comment by vruzicka** [comment]
I have verified with an old version 1.00.219 which seems to work. Please see the attached screenshot.
![dsapp-old-version-219-ok](https://cloud.githubusercontent.com/assets/20126963/18167439/e0fe122e-7050-11e6-80ce-27921743bbae.PNG)

**Comment by snielson** [comment]
Hi Volkmar,

Thanks for submitting a new issue.
I have ISO check to make sure the ISO is a mobility ISO, by checking the info on the ISO itself.
I was pretty sure there was a option to continue anyways, but will look into this.

Perhaps the method I use (isoinfo) to get the info from the ISO isn't on "reduced" version of SLES 11
Could you paste the results of the following command:

`isoinfo -i /path/to/iso -x "/CONTENT.;1"`

**Comment by vruzicka** [comment]
Hello,
sorry to let you know that now on a "normal" gms sles11 sp4 release server the ISO update feature does not work anymore. When selected it does not do anything. 
See screenshots from v238 and v240. 
Volkmar
![dsapp-v238-ok](https://cloud.githubusercontent.com/assets/20126963/18466156/cc4d13ae-799a-11e6-8c56-b4c02064802f.jpg)
![dsapp-v240-notok](https://cloud.githubusercontent.com/assets/20126963/18466158/cc54db34-799a-11e6-92b9-8a3b02cda593.jpg)

**Comment by snielson** [comment]
Super strange! My return of the ISO path was deleted by mistake.
I updated the auto update zip, and v240 release.

Please uninstall, and redownload for the fixed v240

**Comment by snielson** [comment]
Looks like the missing return was on this [commit](https://github.com/snielson/dsapp_python/commit/fc8e5f32c4a8b38eaa094337397e92df5b54f63c)
Let me know if this now works again for you.

**Comment by snielson** [comment]
Closing issue as workaround added
