### ISSUE TITLE
Groupwise Folder Structure check

### ISSUE THREAD

**Issue by korth1** [snielson/dsapp_python#34]
We use v2.40 from dsapp, and i work now a few times with the option 5,2,2 The Check Groupwise Folder structure. It's very good to have this, because GMS is not working properly went there is something with the structure. My question now is, what if dsapp has found a structure problem. Can it also repair this, without losing data? Now it gives a messages that there is a structure problem with, by example, the calendar. But the next step is to repair this. Or are there already tools for, to handle such a structure failure. Kind regards, Henk Korterink

**Comment by snielson** [comment]
Hmm I haven't thought about including an option to fix this with dsapp, but may be very possible (depending on SOAP).

Currently if there are folder structure issues found, we require the user to log into their client, and manually fix the structure (drag back to the correct location), and reinit the user.

I'll do some research on available solutions with SOAP, and perhaps I can include an option to fix with dsapp.

**Comment by snielson** [comment]
Yeah I am working with GroupWise dev for fixing folder structure with dsapp. We can use the modifyItem SOAP request, and change the parent ID of a folder. This should result in the folders being moved to the correct locations.

I'd be happy to look at a mcheck log if you'd like to email it directly to me? This should give me more information why dsapp is reporting the contact wrong, and maybe we can see where it think it is at.
snielson@projectuminfinitas.com

`cd /opt/novell/datasync/tools/mcheck`
`python mcheck.pyc`
Run a user check on the problem user ID. Exit mcheck, and the log should be in /opt/novell/datasync/tools/mcheck/logs/

**Comment by snielson** [comment]
Making progress on having dsapp fix the folder structure via SOAP.
Should have a test build this weekend (hopefully)

**Comment by snielson** [comment]
This new build of dsapp v241 should prompt to fix folder structure if wrong (after checking).
Let me know if this works on your end, and if I can fix anything (including format / wording)

Thanks!
[dsapp-241v1.zip](https://github.com/snielson/dsapp_python/files/601882/dsapp-241v1.zip)

**Comment by korth1** [comment]
Hello Shane,

This is working !!

I tried this on the problem mailbox, and now the 'contacts' folder is
back again.

I have not yet spoken to the user, to verify is the sync to the mobile
device also is working again, but i let you know.

I have attach a word document, with the text has we see it. 

GREAT JOB !!!


vrgr 


Henk Korterink
iLentis, afdeling Automatisering
t 050 4097400
f 050 4097433
e h.korterink@lentis.nl
 
P Denk alstublieft aan het milieu - is het echt nodig deze mail te
printen?
Indien u gebruik maakt van een navigatie systeem om naar de lokatie te
komen, kunt u het beste Stationsweg 163 Zuidlaren invoeren. 
Recht tegenover dit adres vindt u de hoofdingang van het Lentis
terrein. 
Op het terrein staat het betreffende gebouw aangegeven op de
bebording.




Disclaimer

Lentis heeft zijn aansprakelijkheid ten aanzien van inhoud en verzending
van dit bericht beperkt. Bekijk
http://www.lentis.nl/OverLentis/Disclaimer/E-mail.aspx om de volledige
tekst van de e-mail disclaimer te lezen.

>>> Shane <notifications@github.com> 20-11-2016 7:12 >>>
This new build of dsapp v241 should prompt to fix folder structure if
wrong (after checking).
Let me know if this works on your end, and if I can fix anything
(including format / wording)
Thanks!
dsapp-241v1.zip
(
https://github.com/snielson/dsapp_python/files/601882/dsapp-241v1.zip) 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/snielson/dsapp_python/issues/34#issuecomment-261761300)
, or mute the thread
(

**Comment by snielson** [comment]
Great to hear it's working, also remember to re-init the user after fixing their folder structure. I'll add a message in dsapp about this.

**Comment by snielson** [comment]
Option to fix folder structure in dsapp v242
Closing defect

**Comment by korth1** [comment]
Hello Shane,

Problem is solved. synchronisation is working again for this account.

Thank you very much !!
And your dsapp tool is again better than it was.


kind regards,


Henk Korterink
iLentis, afdeling Automatisering
t 050 4097400
f 050 4097433
e h.korterink@lentis.nl
 
P Denk alstublieft aan het milieu - is het echt nodig deze mail te
printen?
Indien u gebruik maakt van een navigatie systeem om naar de lokatie te
komen, kunt u het beste Stationsweg 163 Zuidlaren invoeren. 
Recht tegenover dit adres vindt u de hoofdingang van het Lentis
terrein. 
Op het terrein staat het betreffende gebouw aangegeven op de
bebording.




Disclaimer

Lentis heeft zijn aansprakelijkheid ten aanzien van inhoud en verzending
van dit bericht beperkt. Bekijk
http://www.lentis.nl/OverLentis/Disclaimer/E-mail.aspx om de volledige
tekst van de e-mail disclaimer te lezen.

>>> Shane <notifications@github.com> 21-11-2016 23:04 >>>
Great to hear it's working, also remember to re-init the user after
fixing their folder structure. I'll add a message in dsapp about this.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(
https://github.com/snielson/dsapp_python/issues/34#issuecomment-262082197)
, or mute the thread
(
