### ISSUE TITLE
Hostname Error

### ISSUE THREAD

**Issue by jesullivan** [snielson/dsapp_python#35]
Our mobility server was recently upgraded.  During the upgrade the hostname was changed.  Since then we're getting the following error when starting dsapp:   Unable to read encryption with current hostname 'xxxxx'.   If we tell the utility to fix the issue we get the following error:  bad decrypt - error decoding .//configengine/ldap/login/password.  We have only had two hostnames and neither works.  What can we do to get this working?

**Comment by snielson** [comment]
Did you try the -ch switch and use the fully qualified hostname?

If neither one of those work, and you know where you trusted application file is at, you can use the -cl or --clear switch to set everything back to cleartext.

**Comment by jesullivan** [comment]
Yeah I've tried the ch switch.  Is the trusted application file the only thing needed if the clear switch is used?  I assume system passwords have to be reentered?  Thanks for your help!

**Comment by snielson** [comment]
It's really the only thing needed that cannot be changed (very easy).
The other passwords can actually be changed,

For example, if you use LDAP, you can put whatever you want for that password, and change whenever from the config > user source (long as you log in with root).
The database password can be changed with the -db switch in dsapp.

Let me know how it goes :)

**Comment by jesullivan** [comment]
I was having problems getting the -cl switch to work as well.  I finally discovered that the hostname in settings.cfg was incorrect to start with.  After updating that I was able to access the dsapp main menu.  Thanks for your help and quick responses.
