### ISSUE TITLE
Possible python issue?

### ISSUE THREAD

**Issue by kevinrsalisbury** [snielson/dsapp_python#36]
Shane - I have a strange one for you. Is it possible there are python issues?

SLES 11 SP4 x64 - GMS Version: 14.2.1 Build: 284 - dsapp 2.00-244

Updated SLES yesterday complete and rebooted. Now dsapp won't run. Python issues perhaps? 

server:/opt/novell/datasync/tools # zypper install dsapp-2.00-244.noarch.rpm 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW package is going to be installed:
  dsapp 

The following package is not supported by its vendor:
  dsapp 

1 new package to install.
Overall download size: 4.1 MiB. After the operation, additional 13.9 MiB will be used.
Continue? [y/n/? shows all options] (y): y
Retrieving package dsapp-2.00-244.noarch (1/1), 4.1 MiB (13.9 MiB unpacked)
Retrieving package dsapp-2.00-244.noarch (1/1), 4.1 MiB (13.9 MiB unpacked)
Installing: dsapp-2.00-244 [done]

**server:/opt/novell/datasync/tools # dsapp
Traceback (most recent call last):
  File "/opt/novell/datasync/tools/dsapp/dsapp.py", line 170, in <module>
    import dsapp_Definitions as ds
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_Definitions.py", line 35, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'disable_warnings'**

server:/opt/novell/datasync/tools # zypper info dsapp
Loading repository data...
Reading installed packages...

Information for package dsapp:

Repository: @System
Name: dsapp
Version: 2.00-244
Arch: noarch
Vendor: 
Support Level: unknown
Installed: Yes
Status: up-to-date
Installed Size: 13.9 MiB
Summary: Server-side tool for Novell Groupwise Mobility Services
Description: 
dsapp helps customers and engineers troubleshoot and solve common issues for the Novell GroupWise Mobility product. dsapp.sh is designed to be a server-side tool aimed to help troubleshoot and solve common issues.

Please submit bug fixes or comments to:
    Shane Nielson <snielson@[spam protection].com>

twindsync:/opt/novell/datasync/tools # zypper info python
Loading repository data...
Reading installed packages...

server::/opt/novell/datasync/tools # zypper info python
Information for package python:

Repository: SLES11-SP4-Updates
Name: python
Version: 2.6.9-39.1
Arch: x86_64
Vendor: SUSE LINUX Products GmbH, Nuernberg, Germany
Support Level: Level 3
Installed: Yes
Status: up-to-date
Installed Size: 1.1 MiB
Summary: Python Interpreter
Description: 
Python is an interpreted, object-oriented programming language, and is
often compared to Tcl, Perl, Scheme, or Java.  You can find an overview
of Python in the documentation and tutorials included in the python-doc
(HTML) or python-doc-pdf (PDF) packages.

**Comment by snielson** [comment]
The requests module is (or should be) included with dsapp in the lib directory.
Can you verify the lib directory still has requests?

/opt/novell/datasync/tools/dsapp/lib/requests
or more specific
/opt/novell/datasync/tools/dsapp/lib/requests/packages/urllib3/

**Comment by kevinrsalisbury** [comment]
urllib3 is there: 
server::/opt/novell/datasync/tools/dsapp/lib/requests/packages/urllib3 # ll
total 268
-rwxr--r-- 1 root root 10553 Jan 24 02:57 _collections.py
-rwxr--r-- 1 root root 13690 Jan 24 02:57 _collections.pyc
-rwxr--r-- 1 root root 33591 Jan 24 02:57 connectionpool.py
-rwxr--r-- 1 root root 26317 Jan 24 02:57 connectionpool.pyc
-rwxr--r-- 1 root root 11617 Jan 24 02:57 connection.py
-rwxr--r-- 1 root root 10525 Jan 24 02:57 connection.pyc
drwxr-xr-x 2 root root  4096 Feb 20 07:45 contrib
-rwxr--r-- 1 root root  5599 Jan 24 02:57 exceptions.py
-rwxr--r-- 1 root root 11705 Jan 24 02:57 exceptions.pyc
-rwxr--r-- 1 root root  5931 Jan 24 02:57 fields.py
-rwxr--r-- 1 root root  6920 Jan 24 02:57 fields.pyc
-rwxr--r-- 1 root root  2320 Jan 24 02:57 filepost.py
-rwxr--r-- 1 root root  3392 Jan 24 02:57 filepost.pyc
-rwxr--r-- 1 root root  2852 Jan 24 02:57 __init__.py
-rwxr--r-- 1 root root  3324 Jan 24 02:57 __init__.pyc
drwxr-xr-x 4 root root  4096 Feb 20 07:45 packages
-rwxr--r-- 1 root root 13092 Jan 24 02:57 poolmanager.py
-rwxr--r-- 1 root root 13020 Jan 24 02:57 poolmanager.pyc
-rwxr--r-- 1 root root  5988 Jan 24 02:57 request.py
-rwxr--r-- 1 root root  6211 Jan 24 02:57 request.pyc
-rwxr--r-- 1 root root 18615 Jan 24 02:57 response.py
-rwxr--r-- 1 root root 17311 Jan 24 02:57 response.pyc
drwxr-xr-x 2 root root  4096 Feb 20 07:45 util
-rwxr-xr-x 1 root root 3276 Jan 13 13:15 update.sh
-rw-r--r-- 1 root root   11 Jan 13 13:28 version
drwxr-xr-x 5 root root 4096 Jan 13 13:28 webadmin

and here's the contents of requests;
server:/opt/novell/datasync/tools/dsapp/lib/requests # dir
total 712
-rwxr--r-- 1 root root  19727 Jan 24 02:57 adapters.py
-rwxr--r-- 1 root root  18020 Jan 24 02:57 adapters.pyc
-rwxr--r-- 1 root root   5960 Jan 24 02:57 api.py
-rwxr--r-- 1 root root   6737 Jan 24 02:57 api.pyc
-rwxr--r-- 1 root root   8203 Jan 24 02:57 auth.py
-rwxr--r-- 1 root root   8947 Jan 24 02:57 auth.pyc
-rwxr--r-- 1 root root 344712 Jan 24 02:57 cacert.pem
-rwxr--r-- 1 root root    625 Jan 24 02:57 certs.py
-rwxr--r-- 1 root root    887 Jan 24 02:57 certs.pyc
-rwxr--r-- 1 root root   1627 Jan 24 02:57 compat.py
-rwxr--r-- 1 root root   1833 Jan 24 02:57 compat.pyc
-rwxr--r-- 1 root root  18291 Jan 24 02:57 cookies.py
-rwxr--r-- 1 root root  21913 Jan 24 02:57 cookies.pyc
-rwxr--r-- 1 root root   2976 Jan 24 02:57 exceptions.py
-rwxr--r-- 1 root root   6349 Jan 24 02:57 exceptions.pyc
-rwxr--r-- 1 root root    767 Jan 24 02:57 hooks.py
-rwxr--r-- 1 root root   1200 Jan 24 02:57 hooks.pyc
-rwxr--r-- 1 root root   2197 Jan 24 02:57 __init__.py
-rwxr--r-- 1 root root   2818 Jan 24 02:57 __init__.pyc
-rwxr--r-- 1 root root    715 Jan 24 02:57 _internal_utils.py
-rwxr--r-- 1 root root    967 Jan 24 02:57 _internal_utils.pyc
-rwxr--r-- 1 root root  31941 Jan 24 02:57 models.py
-rwxr--r-- 1 root root  26866 Jan 24 02:57 models.pyc
drwxr-xr-x 5 root root   4096 Feb 20 07:45 packages
-rwxr--r-- 1 root root  26216 Jan 24 02:57 sessions.py
-rwxr--r-- 1 root root  21154 Jan 24 02:57 sessions.pyc
-rwxr--r-- 1 root root   3316 Jan 24 02:57 status_codes.py
-rwxr--r-- 1 root root   4736 Jan 24 02:57 status_codes.pyc
-rwxr--r-- 1 root root   3012 Jan 24 02:57 structures.py
-rwxr--r-- 1 root root   5203 Jan 24 02:57 structures.pyc
-rwxr--r-- 1 root root  24823 Jan 24 02:57 utils.py
-rwxr--r-- 1 root root  23244 Jan 24 02:57 utils.pyc

**Comment by snielson** [comment]
Did the latest OS update add its own version of requests?
Can you run the following commands from any directory, on the GMS server (excluding the dsapp/lib directory)
```
python
import requests
```
It should error out with a _ImportError: No module named requests_

However if it does work.. follow up with 
`print requests.__version__`

**Comment by kevinrsalisbury** [comment]
server:~ # python
Python 2.6.9 (unknown, Aug  5 2016, 11:15:31)
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> print requests.__version__
2.0.1
>>>

**Comment by kevinrsalisbury** [comment]
Shane - a couple of days prior we did [install the standard stable python salt-minion](https://docs.saltstack.com/en/latest/topics/installation/suse.html#stable-release) agent prior to this dsapp issue (we're strongly considering Suse Manager here and I don't think we can use the salt-ssh minion connector yet). The salt-minion was completely removed as part of troubleshooting through, however I wonder if a left over python configuration for the salt-minion agent could be part of the issue?

**Comment by snielson** [comment]
Well since I included requests with dsapp, I just need to force dsapp to use that version. I should have something to test later today.

**Comment by snielson** [comment]
Before I commit this change, can you test this.

Edit /opt/novell/datasync/tools/dsapp/dsapp.py
Change line 39

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + '/lib')
to
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/lib')

**Comment by kevinrsalisbury** [comment]
<...>
if not os.path.exists('/opt/novell/datasync/tools/dsapp/logs/'):
        os.makedirs('/opt/novell/datasync/tools/dsapp/logs/')                       sys.path.insert(0, os.path.dirname(os.path.realpath(file)) + '/lib')
import spin
import imp                                                                          @
<...>                                                                                   "dsapp.py" 694L, 28695C written                                                     
server:/opt/novell/datasync/tools/dsapp # dsapp
Traceback (most recent call last):
  File "/opt/novell/datasync/tools/dsapp/dsapp.py", line 39, in <module>
    sys.path.insert(0, os.path.dirname(os.path.realpath(file)) + '/lib')
  File "/usr/lib64/python2.6/posixpath.py", line 357, in realpath
    if isabs(filename):
  File "/usr/lib64/python2.6/posixpath.py", line 52, in isabs
    return s.startswith('/')
AttributeError: type object 'file' has no attribute 'startswith'
server:/opt/novell/datasync/tools/dsapp #

**Comment by snielson** [comment]
Sorry about that.. the comment for some reason removed some characters

It should be 
`sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/lib')`
not
`sys.path.insert(0, os.path.dirname(os.path.realpath(file)) + '/lib')`

**Comment by kevinrsalisbury** [comment]
Seems to work fine now! Thanks!

**Comment by snielson** [comment]
Resolved in c172e9a55d7ac59935db00022294f717535d80c4
