### ISSUE TITLE
Find shared folder which have no recipient

### ISSUE THREAD

**Issue by mfaust78** [snielson/dsapp_python#38]
As systems live it can happen that shared folders are still marked as shared (isSharedByMe = True), but no recipient (no ACL) are there anymore. Simple to create: User A shares to User B, User B accepts, User B is deleted --> Shared folder in User A looks like this one:
(SharedFolder){
               id = "52205792.do-bs7.po-bs7.100.1326472.1.3135.1@35"
               sid = 12597
               name = "206'496'xxx Metalli"
               modified = 2017-02-08 12:17:21
               parent = "4E57D4B4.do-basel.po-gel.100.1326472.1.CB9.1@13"
               sequence = 0
               isSharedByMe = True
},

Would it be possible to create a dsapp option to search for such folders and show them to the admin? Also great would be a search for System Folders that are shared (e.g. Mailbox - was possible some moons ago but dsapp does not like it).

If it is too much trouble, just close the issue with "won't fix".
Thanks.

**Comment by snielson** [comment]
Yeah I can look into this. This never crossed my mind that someone could have a shared folder with no recipient.

Are you looking for a check that searches every GroupWise user, or only users synced to GMS?

**Comment by mfaust78** [comment]
Thanks for looking into it. As I think it might affect the GMS users it would be good to have a check that checks all GMS users or specific Users from GW.

**Comment by snielson** [comment]
Reviewed this issue again, and after some testing, I believe GroupWise should handle this.
Issue has been reported to GroupWise dev team.

IMO GroupWise code should remove the sharedFolder attribute once all recipients have been removed / deleted.
