### ISSUE TITLE
Not detecting Open VM tools, so health check complains.

### ISSUE THREAD

**Issue by ChaosAdventurer** [snielson/dsapp_python#39]
==========================================================
Checking VMware-tools..
==========================================================
Server is running within a virtualized platform
/etc/init.d/vmware-tools is not running

but vSphere Version 6.0.0 Build 3617395 happily says on the matter for this vm
   Running, version:2147483647 (Guest Managed)

SLES12.2 fresh install,  vmtools installed without replacing open vm tools, but to supplement with drivers.
GMS 14.2.2.2 and dsapp managed to get through running the health check even though no users added yet.  Some errors along the way but managed to deal with them satisfactorily.

**Comment by snielson** [comment]
My fresh SLES 12 VM happens to pass the check, however this is not running on ESXI.
The check is kind of crude, as it just runs a status on the scripts in /etc/init.d/

Does your server not use /etc/init.d/vmware-tools-service or /etc/init.d/vmware-tools ?
If you have another file it should check with the 'status' command, please let me know.

**Comment by ChaosAdventurer** [comment]
‎Hi ShaneI'm not sure exactly what is handling the vm tools bit, only that when I went to add vmware's vmtools to this system, it observed that Open VM Tools was already present and would I link to just update the relevant drivers (yes)I recall that Open VM Tools is a new feature of SLES 12 and I haven't yet doven into the details of it yet. (SLES12.2 on vSphere 6.0) If a thing is working, why dive into the details when there are so many other things to play with‎?  I doubt it will be an init.d based, but rather systemd based.I'll send some screen shots seperately, they are on the notebook, I wrote this on my mobile.‎Speaking of other things, Let'sEncrypt, I appear to have it functioning on this system and think a CoolSolution about this would be a very good idea. Is this something you are interested in doing or being a part of?  I've started drafting some notes in that direction, but don't want trip over you if you are about to submit such a thing.                                                                                                                                                                                                                                                                                                                                        Andy of KonecnyConsulting.ca                                                                                                                                                                                                                From: ShaneSent: Thursday, September 7, 2017 19:19To: snielson/dsapp_pythonReply To: snielson/dsapp_pythonCc: Andy Konecny; AuthorSubject: Re: [snielson/dsapp_python] Not detecting Open VM tools, so health check complains. (#39)My fresh SLES 12 VM happens to pass the check, however this is not running on ESXI.
The check is kind of crude, as it just runs a status on the scripts in /etc/init.d/
Does your server not use /etc/init.d/vmware-tools-service or /etc/init.d/vmware-tools ?
If you have another file it should check with the 'status' command, please let me know.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/snielson/dsapp_python","title":"snielson/dsapp_python","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/snielson/dsapp_python"}},"updates":{"snippets":[{"icon":"PERSON","message":"@snielson in #39: My fresh SLES 12 VM happens to pass the check, however this is not running on ESXI.\r\nThe check is kind of crude, as it just runs a status on the scripts in /etc/init.d/\r\n\r\nDoes your server not use /etc/init.d/vmware-tools-service or /etc/init.d/vmware-tools ?\r\nIf you have another file it should check with the 'status' command, please let me know."}],"action":{"name":"View Issue","url":"https://github.com/snielson/dsapp_python/issues/39#issuecomment-327953600"}}}

**Comment by ChaosAdventurer** [comment]
2nd part, screen shots mentioned in 1st part

I think the systemd way would be to test if the service is present (Not 
"not-found") and is loaded, active, and running.  I guess part of test 
would be is this an init.d or systemd system?
Here are some shots from this SLES12.2 on vSphere 6.0 system that is the 
same as in SR#101098703481 if any of that data helps.

gms:~ # systemctl list-units |grep gms
gms.service             loaded active exited    LSB: Start datasync 
services

gms:~ # systemctl list-units |grep tools
vgauthd.service         loaded active running   open-vm-tools: vgauth 
service for virtual machines hosted on VMware
vmtoolsd.service        loaded active running   open-vm-tools: vmtoolsd 
service for virtual machines hosted on VMware
vmware-tools.service    loaded active exited    LSB: VMware Tools 
service

gms:~ # systemctl status vmtoolsd.service
? vmtoolsd.service - open-vm-tools: vmtoolsd service for virtual 
machines hosted on VMware
    Loaded: loaded (/usr/lib/systemd/system/vmtoolsd.service; enabled; 
vendor preset: enabled)
    Active: active (running) since Wed 2017-09-06 18:01:10 EDT; 1 day 3h 
ago
      Docs: http://github.com/vmware/open-vm-tools
   Process: 1320 ExecStart=/usr/bin/vmtoolsd --background 
/var/run/vmtoolsd.pid (code=exited, status=0/SUCCESS)
  Main PID: 1441 (vmtoolsd)
     Tasks: 1 (limit: 512)
    CGroup: /system.slice/vmtoolsd.service
            +-1441 /usr/bin/vmtoolsd

Sep 06 18:01:09 gms systemd[1]: Starting open-vm-tools: vmtoolsd service 
for virtual machines hosted on VMware...
Sep 06 18:01:10 gms systemd[1]: Started open-vm-tools: vmtoolsd service 
for virtual machines hosted on VMware.

gms:~ # systemctl status vmware-tools.service
? vmware-tools.service - LSB: VMware Tools service
    Loaded: loaded (/etc/init.d/vmware-tools; bad; vendor preset: 
disabled)
    Active: active (exited) since Wed 2017-09-06 18:01:18 EDT; 1 day 3h 
ago
      Docs: man:systemd-sysv-generator(8)
   Process: 1318 ExecStart=/etc/init.d/vmware-tools start (code=exited, 
status=0/SUCCESS)
     Tasks: 0 (limit: 512)

Sep 06 18:01:09 gms systemd[1]: Starting LSB: VMware Tools service...
Sep 06 18:01:10 gms vmware-tools[1318]: [35B blob data]
Sep 06 18:01:10 gms vmware-tools[1318]: Starting VMware Tools services 
in the virtual machine:
Sep 06 18:01:17 gms vmware-tools[1318]: [46B blob data]
Sep 06 18:01:18 gms vmware-tools[1318]: [36B blob data]
Sep 06 18:01:18 gms systemd[1]: Started LSB: VMware Tools service.

gms:~ # systemctl status randomexample.service
? randomexample.service
    Loaded: not-found (Reason: No such file or directory)
    Active: inactive (dead)

gms:~ #

**Comment by snielson** [comment]
I've only set up the LetsEncrypt, but have not wrote up any notes on it. Someone posted to the Novell forums some time ago with steps that work great without any other files (except a simple bash script).
If you have notes for a cool solution, please write them up, as I'm sure many would find them useful!

Since starting dsapp with SLES11, it has been a bumpy road to make it backwards compatible with SLES12. I believe most things work now, but with more and more moving to SLES12, I think it's time the script does a service vs. init.d check. I'll see what I can do with your notes. I may have to set up another GMS server on ESXI 6.0

**Comment by snielson** [comment]
Fix checked into commit d06e195c9e6cb6105ac2e5b61d89af43f1ad98c3
Will needs some further testing

Would you mind trying this new build, and let me know if this resolves the health check issue.
[dsapp-246v2.zip](https://github.com/snielson/dsapp_python/files/1294596/dsapp-246v2.zip)

**Comment by snielson** [comment]
dsapp v247 has been pushed with a possible fix.
Reopen if this is still an issue with v247
