### ISSUE TITLE
dsapp on sles 12

### ISSUE THREAD

**Issue by kekeju** [snielson/dsapp_python#43]
Updated my GMS server to 18.0.1 and at the same time SLES 11 SP4 to SLES 12 SP2.
dsapp worked great in SLES 11 but no I just recieve this when I start dsapp.

[dsapp.log](https://github.com/snielson/dsapp_python/files/1846870/dsapp.log)

**Comment by bahsig** [comment]
try uninstalling and reinstalling dsapp.

**Comment by kekeju** [comment]
Hi,

The first attempt to uninstall did not work.
Got the uninstall to work later so now dsapp works great again.

Thanks.
